services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: symfony_backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://symfony:symfony@postgres/symfony
    networks:
      - my_network

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend  # Path to your Dockerfile
    container_name: react_frontend
    ports:
      - "5173:5173"  # Map container port to host port
    volumes:
      - ./frontend:/app  # Bind mount the frontend directory to the container
      - /app/node_modules  # Optional: Prevent the host from using the container's node_modules
    command: ["yarn", "dev"]  # Start the Vite development server
    networks:
      - my_network


  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
