services:
  backend-auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend-auth
    container_name: auth_backend
    ports:
      - "3100:3000"
    volumes:
      - ./backend-auth:/auth
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://symfony:symfony@postgres/symfony"
      REFRESH_TOKEN_KEY: "refresh"
      JWT_SECRET_KEY: "jwt"
      REFRESH_EXPIRATION_TIME: "30d"
      JWT_EXPIRATION_TIME: "15min"
    networks:
      - my_network


  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend  # Path to your Dockerfile
    container_name: react_frontend
    ports:
      - "5200:5173"  # Map container port to host port
    volumes:
      - ./frontend:/app  # Bind mount the frontend directory to the container
      - /app/node_modules  # Optional: Prevent the host from using the container's node_modules
    command: ["yarn", "dev"]  # Start the Vite development server
    environment:
      NODE_ENV: development
      VITE_FETCH_API: "http://localhost:3100"
    networks:
      - my_network


  postgres:
    image: postgres:17
    container_name: postgres_db
    ports:
      - "5600:5433"
    environment:
      POSTGRES_DB: "symfony"
      POSTGRES_USER: "symfony"
      POSTGRES_PASSWORD: "symfony"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
